master.varname = {...
'AIRTEMP','AIRTEMP';...
'COND','COND';...
'H','H';...
'Nitrite','Nitrite';...
'PRECIP','PRECIP';...
'RELHUM','RELHUM';...
'SAL','SAL';...
'SECCHI_DEPTH','SECCHI_DEPTH';...
'TEMP','TEMP';...
'WQ_CAR_PH','WQ_CAR_PH';...
'WQ_DIAG_OXY_SAT','WQ_DIAG_OXY_SAT';...
'WQ_DIAG_PHY_TCHLA','WQ_DIAG_PHY_TCHLA';...
'WQ_DIAG_TOT_TKN','WQ_DIAG_TOT_TKN';...
'WQ_DIAG_TOT_TN','WQ_DIAG_TOT_TN';...
'WQ_DIAG_TOT_TP','WQ_DIAG_TOT_TP';...
'WQ_DIAG_TOT_TSS','WQ_DIAG_TOT_TSS';...
'WQ_DIAG_TOT_TURBIDITY','WQ_DIAG_TOT_TURBIDITY';...
'WQ_NIT_AMM','WQ_NIT_AMM';...
'WQ_NIT_NIT','WQ_NIT_NIT';...
'WQ_OXY_OXY','WQ_OXY_OXY';...
'phaeophytin_a','phaeophytin_a';...
'wind_direction_std','wind_direction_std';...
};

timeseries.start_plot_ID = 1;
timeseries.end_plot_ID = 22;
