function getBoMmetdata(sMetDir)
% Function to import the swan met data and save to a structured type
% swanmet.mat
% sMetDir is the file path in which the BoM data files are stored. Remember
% to add "\" at the end of the path!!!
% Add or remove headers under cHeader based on your data. Import of Date in
% the right format should be checked!

dirlist = dir(sMetDir);

for iMet = 3:length(dirlist)
    
    disp(['Processing File ',num2str(iMet - 2)]);
    filename = [sMetDir,dirlist(iMet).name];
    fid = fopen(filename,'rt');
    
    
    cHeader = { ...
        'hm_QC';...
        'StationID';...
        'Date';...
        'Rain_9am';...
        'Rain_9am_QC';...
        'AirTemperature';...
        'AirTemperature_QC';...
        'WetBulbTemperature';...
        'WetBulbTemperature_QC';...
        'DewPoint';...
        'DewPoint_QC';...
        'RelativeHumidity';...
        'RelativeHumidity_QC';...
        'WindSpeed';...
        'WindSpeed_QC';...
        'WindDir';...
        'WindDir_QC';...
        'WindSpeedMax_10min';...
        'WindSpeeedMax_10min_QC';...
        'CloudAmount_First';...
        'CloudAmount_First_QC';...
        'CloudHeight_First';...
        'CloudHeight_First_QC';...
        'CloudAmount_Second';...
        'CloudAmount_Second_QC';...
        'CloudHeight_Second';...
        'CloudHeight_Second_QC';...
        'CloudAmount_Third';...
        'CloudAmount_Third_QC';...
        'CloudHeight_Third';...
        'CloudHeight_Third_QC';...
        'CloudAmount_Fourth';...
        'CloudAmount_Fourth_QC';...
        'CloudHeight_Fourth';...
        'CloudHeight_Fourth_QC';...
        'CeilometerCloudAmount_First';...
        'CeilometerCloudAmount_First_QC';...
        'CeilometerCloudHeight_First';...
        'CeilometerCloudHeight_First_QC';...
        'CeilometerCloudAmount_Second';...
        'CeilometerCloudAmount_Second_QC';...
        'CeilometerCloudHeight_Second';...
        'CeilometerCloudHeight_Second_QC';...
        'CeilometerCloudAmount_Third';...
        'CeilometerCloudAmount_Third_QC';...
        'CeilometerCloudHeight_Third';...
        'CeilometerCloudHeight_Third_QC';...
        'Ceilometer_QC';...
        'AirPressure_MSL';...
        'AirPressure_MSL_QC';...
        'AirPressure_Stn';...
        'AirPressure_Stn_QC';...
        'AWS_Flag_QC';...
        'LineEnd_QC';...
        };
    x  = length(cHeader);
    textformat = [repmat('%s ',1,x)];
    datacell = textscan(fid,textformat,...
        'Headerlines',1,...
        'Delimiter',',');
    fclose(fid);
    
    for iHeader = 1:length(cHeader)
        sCompStrFull = cHeader{iHeader};
        sCompStr = sCompStrFull(end-2:end);
        
        if strcmp(sCompStr,'_QC') == 0
            if strcmp(cHeader{iHeader},'Date') == 1
                met.(cHeader{iHeader}) = datenum(datacell{iHeader},'dd/mm/yyyy HH:MM');
            else
                met.(cHeader{iHeader}) = str2double(datacell{iHeader});
            end
        end
        
    end
    
       
    nSiteID = met.StationID(1);
    
    switch nSiteID
        case 9127
            metdata.mosman_park = met;
            metdata.mosman_park.lat = -32.0200;
            metdata.mosman_park.lon = 115.7692;
        case 9192
            metdata.fremantle = met;
            metdata.fremantle.lat = -32.0533;
            metdata.fremantle.lon = 115.7647;
        case 9215
            metdata.swanbourne = met;
            metdata.swanbourne.lat = -31.9558;
            metdata.swanbourne.lon = 115.7619;
        case 9977
            metdata.mandurah_new = met;
            metdata.mandurah_new.lat = -32.5219;
            metdata.mandurah_new.lon = 115.7119;
        case 9887
            metdata.mandurah_old = met;
            metdata.mandurah_old.lat = -32.5219;
            metdata.mandurah_old.lon = 115.7119;
        case 9538
            metdata.dwellingup = met;
            metdata.dwellingup.lat = -32.7103;
            metdata.dwellingup.lon = 116.0594;
        case 9596
            metdata.pinjarra = met;
            metdata.pinjarra.lat = -32.6272;
            metdata.pinjarra.lon = 115.8747;
        case 9039
            metdata.serpentine = met;
            metdata.serpentine.lat = -32.3536;
            metdata.serpentine.lon = 116.0050;
        case 9115
            metdata.serpentine_dam = met;
            metdata.serpentine_dam.lat = -32.4022;
            metdata.serpentine_dam.lon = 116.1039;
        case 9877
            metdata.ludlow = met;
            metdata.ludlow.lat = -33.6033;
            metdata.ludlow.lon = 115.4983;
        case 9515
            metdata.busselton_shire = met;
            metdata.busselton_shire.lat = -33.6611;
            metdata.busselton_shire.lon = 115.3456;
        case 9569
            metdata.busselton_shire_old = met;
            metdata.busselton_shire_old.lat = -33.6611;
            metdata.busselton_shire_old.lon = 115.3456;
        case 9937
            metdata.busselton_jetty = met;
            metdata.busselton_jetty.lat = -33.6294;
            metdata.busselton_jetty.lon = 115.3383;
        case 9603
            metdata.busselton_aero = met;
            metdata.busselton_aero.lat = -33.6858;
            metdata.busselton_aero.lon = 115.4008;
        case 9021
            metdata.airport = met;
            metdata.airport.lat = -31.9275;
            metdata.airport.lon = 115.9764;
        case 9225
            metdata.metro = met;
            metdata.metro.lat = -31.9192;
            metdata.metro.lon = 115.8728;
        case 9172
            metdata.jandakot = met;
            metdata.jandakot.lat = -32.1011;
            metdata.jandakot.lon = 115.8794;
        otherwise
            disp('StationID not found');
    end
    
    
end

save metdata.mat metdata -mat -v7